### ISSUE TITLE
Current sensor conversion error (mV ->mA)

### ISSUE THREAD

**Issue by van-petrosyan** [cnrabdullah/envio-assessment#1]
Hey @cnrabdullah ,

First of all, thanks for completing the assessment! I am still reviewing the challenge, but I can tell you in advance that your answers are satisfactory! If I find some bugs/errors, I will post in issues.
There is a small error with the conversion of the current sensor value from ADC result to mA. As you can see from the datasheet of the sensor we have two values:

Sensitivity: **400mV**
Zero Current Output Voltage (ZCOV): **1.5V** 

![Screenshot from 2021-08-31 12-09-23](https://user-images.githubusercontent.com/67702374/131484591-8db68a93-c35c-4d70-9197-36928e980dff.png)

and  the conversion formula should be:
`I = (V(ADC) - V(ZCOV)) / SENS`

![Screenshot from 2021-08-31 12-24-39](https://user-images.githubusercontent.com/67702374/131486692-398c4b3b-b948-4186-9128-761d0950dbe2.png)

Best,
Van

**Comment by cnrabdullah** [comment]
Hello @van-petrosyan,

Thank you for your contribution and I'm very glad that you liked the answers!

**Regarding the issue;**

I might have misunderstood the concept while trying to complete the task as soon as possible but I will get through the datasheet again and solve the issue today.

Thank you for the hints!
Abdullah.

**Comment by cnrabdullah** [comment]
I included the `Zero Output Current Voltage` in the current measurement calculation by a substraction in: 0109c4c7a83d5c03342fb5950ceb3b08a26b97e7. It is also sent as an argument to the `CurSensor_Initialize` function.

**Comment by van-petrosyan** [comment]
Yup, now it is correct
